name: Check Outdated Dependencies

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    uses: valkyrjaio/.github/.github/workflows/_check-outdated-java-dependencies.yml@a15724723b7c6668fb26b8c3bec90ddedea44dcb
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Spotless",    "directory": ".github/ci/spotless"},
          {"name": "ArchUnit",    "directory": ".github/ci/archunit"},
          {"name": "ErrorProne",  "directory": ".github/ci/errorprone"},
          {"name": "SpotBugs",   "directory": ".github/ci/spotbugs"},
          {"name": "JUnit",      "directory": ".github/ci/junit"}
        ]
