name: Create a New Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version component to bump (auto, patch, feature, yearly, or rc)'
        required: true
        type: choice
        default: auto
        options:
          - auto
          - patch
          - feature
          - yearly
          - rc

run-name: "Release ${{ inputs.bump }} bump on ${{ github.ref_name }}"

permissions:
  contents: write

jobs:
  release:
    uses: valkyrjaio/.github/.github/workflows/_java-create-release.yml@107d65ecb1d2cecc72c4839a53958f09ab753b9a
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
    with:
      bump: ${{ inputs.bump }}
      dependencies: |
        [
          {"name": "Spotless",    "directory": ".github/ci/spotless"},
          {"name": "ArchUnit",    "directory": ".github/ci/archunit"},
          {"name": "ErrorProne",  "directory": ".github/ci/errorprone"},
          {"name": "SpotBugs",   "directory": ".github/ci/spotbugs"},
          {"name": "JUnit",      "directory": ".github/ci/junit"}
        ]
      info-class-path: src/main/java/io/valkyrja/application/constant/ApplicationInfo.java
      info-class-name: ApplicationInfo

  publish:
    needs: release
    uses: valkyrjaio/.github/.github/workflows/_java-release-maven-publish.yml@107d65ecb1d2cecc72c4839a53958f09ab753b9a
    secrets:
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      MAVEN_SIGNING_KEY: ${{ secrets.MAVEN_SIGNING_KEY }}
      MAVEN_SIGNING_KEY_PASSWORD: ${{ secrets.MAVEN_SIGNING_KEY_PASSWORD }}
